"""Refactor #97 : Class becomes universal (drop academic_year_id).

Marcel mental model: a school's classes (6ème A, 5ème A, ...) are permanent.
Year-over-year, students enroll/leave but the class identity persists.

Migration steps :
1. Dedupe Class rows : keep MAX(id) per name, repoint FK to canonical row,
   delete duplicates.
2. Drop UniqueConstraint(name, academic_year_id), drop FK to academic_years,
   drop column, drop index.
3. Add UniqueConstraint(name) standalone.

Downgrade : restore column NULL, populate via current AY (best-effort, lossy
on historical AY context — acceptable as documented in plan-and-confirm).

FK orphans repointed (direct class_id FK):
    enrollments, timetable_slots, evaluations, bulletins, council_minutes.
Polymorphic FK (entity_type='class' + context_id) repointed:
    attendance_contexts.

Revision ID: 0022
Revises: 0021
Create Date: 2026-04-28
"""

import sqlalchemy as sa

from alembic import op

revision = "0022"
down_revision = "0021"
branch_labels = None
depends_on = None


# Tables with direct FK pointing to classes.id — repointed via t.class_id.
_DIRECT_FK_TABLES = (
    "enrollments",
    "timetable_slots",
    "evaluations",
    "bulletins",
    "council_minutes",
)


def upgrade() -> None:
    # Step 1: Dedupe — keep MAX(id) per name, repoint FK from old to new.
    # Use a regular table instead of TEMPORARY because aiomysql connections
    # aren't guaranteed to keep TEMPORARY visibility across statements in
    # the same Alembic migration context.
    op.execute("DROP TABLE IF EXISTS class_dedup_map")
    op.execute(
        """
        CREATE TABLE class_dedup_map AS
        SELECT c.id AS old_id,
               (SELECT MAX(c2.id) FROM classes c2 WHERE c2.name = c.name) AS new_id
        FROM classes c
        WHERE c.id != (SELECT MAX(c2.id) FROM classes c2 WHERE c2.name = c.name)
        """
    )

    for table in _DIRECT_FK_TABLES:
        op.execute(
            f"""
            UPDATE {table} t
            JOIN class_dedup_map m ON t.class_id = m.old_id
            SET t.class_id = m.new_id
            """
        )

    # attendance_contexts uses polymorphic (entity_type, context_id) — only
    # repoint rows where entity_type='class' (exam contexts are independent).
    op.execute(
        """
        UPDATE attendance_contexts t
        JOIN class_dedup_map m ON t.context_id = m.old_id
        SET t.context_id = m.new_id
        WHERE t.entity_type = 'class'
        """
    )

    op.execute("DELETE FROM classes WHERE id IN (SELECT old_id FROM class_dedup_map)")
    op.execute("DROP TABLE class_dedup_map")

    # Step 2: Drop the composite UniqueConstraint, FK, index, column.
    # The default constraint and FK names are autogenerated by MySQL —
    # resolve them dynamically rather than hardcode.
    bind = op.get_bind()

    fk_row = bind.execute(
        sa.text(
            """
            SELECT CONSTRAINT_NAME FROM information_schema.KEY_COLUMN_USAGE
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'classes'
              AND COLUMN_NAME = 'academic_year_id'
              AND REFERENCED_TABLE_NAME = 'academic_years'
            LIMIT 1
            """
        )
    ).scalar()
    if fk_row:
        op.drop_constraint(fk_row, "classes", type_="foreignkey")

    uq_row = bind.execute(
        sa.text(
            """
            SELECT INDEX_NAME FROM information_schema.STATISTICS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'classes'
              AND NON_UNIQUE = 0
              AND INDEX_NAME != 'PRIMARY'
              AND COLUMN_NAME IN ('name', 'academic_year_id')
            GROUP BY INDEX_NAME
            HAVING COUNT(*) >= 2
            LIMIT 1
            """
        )
    ).scalar()
    if uq_row:
        op.drop_constraint(uq_row, "classes", type_="unique")

    idx_row = bind.execute(
        sa.text(
            """
            SELECT INDEX_NAME FROM information_schema.STATISTICS
            WHERE TABLE_SCHEMA = DATABASE()
              AND TABLE_NAME = 'classes'
              AND INDEX_NAME != 'PRIMARY'
              AND COLUMN_NAME = 'academic_year_id'
            LIMIT 1
            """
        )
    ).scalar()
    if idx_row:
        op.drop_index(idx_row, table_name="classes")

    op.drop_column("classes", "academic_year_id")

    # Step 3: New UniqueConstraint on name alone (DB-scoped per tenant already)
    op.create_unique_constraint("uq_classes_name", "classes", ["name"])


def downgrade() -> None:
    """Restore column NULL, populate via current AY (best-effort, lossy)."""
    op.drop_constraint("uq_classes_name", "classes", type_="unique")
    op.add_column(
        "classes",
        sa.Column("academic_year_id", sa.BigInteger(), nullable=True),
    )
    op.execute(
        """
        UPDATE classes
        SET academic_year_id = (
            SELECT id FROM academic_years WHERE is_current = 1 LIMIT 1
        )
        """
    )
    op.alter_column(
        "classes",
        "academic_year_id",
        existing_type=sa.BigInteger(),
        nullable=False,
    )
    op.create_foreign_key(
        "classes_ibfk_1",
        "classes",
        "academic_years",
        ["academic_year_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index("ix_classes_academic_year_id", "classes", ["academic_year_id"])
    op.create_unique_constraint(
        "classes_name_academic_year_id_key",
        "classes",
        ["name", "academic_year_id"],
    )
