"""Refactor #97 : Class becomes universal (drop academic_year_id).

Marcel mental model: a school's classes (6ème A, 5ème A, ...) are permanent.
Year-over-year, students enroll/leave but the class identity persists.

Migration steps :
1. Dedupe Class rows : keep MAX(id) per name, repoint 6 FK to canonical row,
   delete duplicates.
2. Drop UniqueConstraint(name, academic_year_id), drop FK to academic_years,
   drop column, drop index.
3. Add UniqueConstraint(name) standalone.

Downgrade : restore column NULL, populate via current AY (best-effort, lossy
on historical AY context — acceptable as documented in plan-and-confirm).

FK orphans repointed: enrollments, timetable_slots, evaluations, bulletins,
attendance_contexts.

Revision ID: 0022
Revises: 0021
Create Date: 2026-04-28
"""

from alembic import op
import sqlalchemy as sa

revision = "0022"
down_revision = "0021"
branch_labels = None
depends_on = None


# Tables with FK pointing to classes.id (all ondelete=RESTRICT) — must be
# repointed to the canonical Class row before deleting duplicates.
_FK_TABLES = (
    "enrollments",
    "timetable_slots",
    "evaluations",
    "bulletins",
    "attendance_contexts",
)


def upgrade() -> None:
    # Step 1: Dedupe — keep MAX(id) per name, repoint FK from old to new
    op.execute(
        """
        CREATE TEMPORARY TABLE class_dedup_map AS
        SELECT c.id AS old_id,
               (SELECT MAX(c2.id) FROM classes c2 WHERE c2.name = c.name) AS new_id
        FROM classes c
        WHERE c.id != (SELECT MAX(c2.id) FROM classes c2 WHERE c2.name = c.name)
        """
    )

    for table in _FK_TABLES:
        op.execute(
            f"""
            UPDATE {table} t
            JOIN class_dedup_map m ON t.class_id = m.old_id
            SET t.class_id = m.new_id
            """
        )

    op.execute("DELETE FROM classes WHERE id IN (SELECT old_id FROM class_dedup_map)")

    # Step 2: Drop the composite UniqueConstraint, FK, index, column
    # MySQL UniqueConstraint name autogenerated — we drop by column list
    op.drop_constraint(
        "classes_name_academic_year_id_key", "classes", type_="unique"
    )
    op.drop_index("ix_classes_academic_year_id", table_name="classes")
    op.drop_constraint("classes_ibfk_1", "classes", type_="foreignkey")
    op.drop_column("classes", "academic_year_id")

    # Step 3: New UniqueConstraint on name alone (DB-scoped per tenant already)
    op.create_unique_constraint("uq_classes_name", "classes", ["name"])


def downgrade() -> None:
    """Restore column NULL, populate via current AY (best-effort, lossy)."""
    op.drop_constraint("uq_classes_name", "classes", type_="unique")
    op.add_column(
        "classes",
        sa.Column("academic_year_id", sa.BigInteger(), nullable=True),
    )
    op.execute(
        """
        UPDATE classes
        SET academic_year_id = (
            SELECT id FROM academic_years WHERE is_current = 1 LIMIT 1
        )
        """
    )
    op.alter_column("classes", "academic_year_id", nullable=False)
    op.create_foreign_key(
        "classes_ibfk_1",
        "classes",
        "academic_years",
        ["academic_year_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    op.create_index(
        "ix_classes_academic_year_id", "classes", ["academic_year_id"]
    )
    op.create_unique_constraint(
        "classes_name_academic_year_id_key",
        "classes",
        ["name", "academic_year_id"],
    )
